# Neurobiologische und kognitive Grundlagen des Spracherwerbs {#sec-neuro}

In diesem Studienjahr haben wir uns auf folgende Themen fokussiert (--> Präsentation in Teams und/oder Internetquellen): 

- **Sensorisches Gedächtnis** (welche Funktion hat es?)

- **Arbeitsgedächtnis** (Welche Beschränkungen hat es? Welche Funktion hat nach Baddelys Modell (a) die phonetische Schleife, (b) der visuelle Notizblock, (c) die zentrale Exekutive? Welche Rolle spielt Aufmerksamkeit für die Aufnahme ins Arbeitsgedächtnis? Wie kann man die Kapazizät des Arbeitsgedächtnisses steigern? 

- Wissenssysteme im **Langzeitgedächtnis** (Welche auffällige Unterschiede gibt es zwischen dem deklarativen und dem prozeduralen Langzeitgedächtnis? Welche (sprachlichen oder nicht-sprachlichen) Reize (Stimuli) haben größere Chancen, im Langzeitgedächtnis gespeichert zu werden? Welchen Einfluss haben emotional geladene Reize auf die Speicherung im Langzeitgedächtnis? Welche Funktion haben der Hippokampus, die Amygdala und frontale Hirnrindenbereiche in Bezug auf die langzeitige Speicherung von Einzelheiten oder Regelmäßigkeiten?) 

