# Entwicklungs- und transferbedingte Fehler {#sec-gender}

Fehler und Abweichungen von der Zielsprache. 

Kormos, Judit

- Anhand welcher Kriterien sind Transfer als Kompetenzphänomen und Interferenz als Performanzphänomen unterscheidbar?
- Welche sprachlichen Bereiche oder Ebenen sind transferanfällig, welche resistenter?
- Was unterscheidet entwicklungsbedingte Fehler von transferbedingten Fehlern?
- Erläutern Sie, warum die Kontrastivhypothese nicht ausreichte, um bestimmte Fehler im Zweit- und Fremdspracherwerb zu erklären und dies zu neuen theoretischen Ansätzen führt (z.B. Identitätshypothese, Interlanguage-Hypothese)?
( s. Teams Zweitspracherwerb: L1 als Hilfe oder Hindernis, Hochländer: Fehlerkunde, Kupisch, Cantone … in meiner Präsentation, Hypothesen von Krashen)


- Beschreiben Sie sprachliche Fehler, die Sie entweder auf einen Einfluss der Erstsprache (Transfer oder Interferenz) oder als entwicklungsbedingte Fehler (die sich nicht auf die L1 zurückführen lassen) einordnen können! 

- Verwenden Sie zu diesem Zweck die Aufsätze der Mittelschüler, die wir schon während des Unterrichts analysiert haben, oder die Aufsätze der Studierenden (Teams: Zweitspracherwerb)! 
